name: mdm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.22.4
  - pytorch=2.4.0
  - torchvision=0.19.0
  - pytorch-cuda=12.4
  - spacy=3.3.1
  - scipy=1.7.3
  - joblib=1.1.0
  - matplotlib=3.4.3
  - moviepy=1.0.3
  - transformers=4.56.1
  - blobfile=3.1.0
  - wandb=0.15.2
  - scikit-learn=1.1.3
  - pip
  - pip:
      - smplx==0.1.28
      - chumpy==0.70
      - git+https://github.com/openai/CLIP.git